name: Generate Snake

on:
  schedule: # run at midnight UTC every day
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2.1.0
        id: generate-snake
        with:
          github_user_name: FonjiHill
          outputs: dist/snake.svg

      - name: Upload the output
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/snake.svg

      - name: Commit and push if there are changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add dist/snake.svg
            git commit -m 'Generate snake animation'
            git push
          else
            echo "No changes to commit"
          fi
